name: BuildTest

on:
  schedule:
    - cron: 0 0 * * *
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    timeout-minutes: 180
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        rosdistro: [galactic, humble]
        include:
          # Galactic Geochelone (May 2021 - November 2022)
          - docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-ros-base-latest
            rosdistro: galactic
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
            rosdistro: humble
          # Rolling Ridley
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-rolling-ros-base-latest
            rosdistro: rolling
    env:
      ROS_DISTRO: ${{ matrix.rosdistro }}
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - uses: actions/checkout@v2-beta
      - name: Check dependency-${{ matrix.rosdistro }}.repos existence
        id: check_rosdistro_repos_files
        uses: andstor/file-existence-action@v1
        with:
          files: dependency-${{ matrix.rosdistro }}.repos
          allow_failure: false
      - name: Check dependency.repos existence
        id: check_repos_files
        uses: andstor/file-existence-action@v1
        with:
          files: dependency.repos
          allow_failure: false
      - name: Run OUXT-Polaris/ros2-ci@master with dependency-${{ matrix.rosdistro }}.repos
        uses: OUXT-Polaris/ros2-ci@master
        if: steps.check_rosdistro_repos_files.outputs.files_exists == 'true'
        with:
          ros2-distro: ${{ matrix.rosdistro }}
          repos-filepath: dependency-${{ matrix.rosdistro }}.repos
      - name: Run OUXT-Polaris/ros2-ci@master with dependency.repos
        uses: OUXT-Polaris/ros2-ci@master
        if: steps.check_rosdistro_repos_files.outputs.files_exists == 'false' && steps.check_repos_files.outputs.files_exists == 'true'
        with:
          ros2-distro: ${{ matrix.rosdistro }}
          repos-filepath: dependency.repos
      - name: Run OUXT-Polaris/ros2-ci@master without repos
        uses: OUXT-Polaris/ros2-ci@master
        if: steps.check_rosdistro_repos_files.outputs.files_exists == 'false' && steps.check_repos_files.outputs.files_exists == 'false'
        with:
          ros2-distro: ${{ matrix.rosdistro }}
      - name: Notify Slack
        uses: 8398a7/action-slack@v2
        if: failure()
        with:
          status: ${{ job.status }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}